/* The following code was generated by JFlex 1.4.3 on 6/16/09 8:42 PM */

package waebric;

/*
@author Rob van der Horst
@author Daniel Weggemans

JFlex specificatie voor Waebric.
*/

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.io.InputStreamReader;
import java.io.InputStream;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/16/09 8:42 PM from the specification file
 * <tt>Z:/F/$user/MoSE/Waebric/jflex/Scanner.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;
  public static final int SITE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\20\1\3\1\2\1\20\1\6\1\1\14\20\6\0\1\3\1\65"+
    "\1\4\1\12\1\56\1\60\1\10\1\23\1\52\1\53\1\21\1\0"+
    "\1\24\1\26\1\17\1\22\12\13\1\67\1\14\1\5\1\61\1\27"+
    "\1\64\1\57\6\16\24\25\1\62\1\7\1\63\1\0\1\11\1\0"+
    "\1\44\1\16\1\45\1\32\1\35\1\43\1\51\1\46\1\36\2\25"+
    "\1\34\1\30\1\47\1\31\1\37\1\25\1\40\1\42\1\41\1\33"+
    "\2\25\1\15\1\50\1\25\1\54\1\66\1\55\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\1\11\6\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\1\1\27\1\1\1\2\1\3\2\6"+
    "\1\13\1\14\1\17\1\20\1\21\1\27\1\1\1\0"+
    "\1\30\1\31\2\0\1\32\3\0\1\33\1\34\2\0"+
    "\11\6\1\35\1\36\6\6\1\37\3\0\1\6\1\0"+
    "\1\40\1\0\1\30\3\0\1\33\2\0\1\6\1\41"+
    "\1\42\4\6\1\43\7\6\1\44\1\45\1\43\1\40"+
    "\4\0\1\6\1\46\1\47\1\50\1\51\2\6\1\52"+
    "\4\6\2\0\5\6\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\6\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\250\0\u0118\0\u0150"+
    "\0\250\0\u0188\0\250\0\u01c0\0\250\0\u01f8\0\u0230\0\250"+
    "\0\u0268\0\u02a0\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0"+
    "\0\u0428\0\u0460\0\250\0\250\0\250\0\250\0\250\0\250"+
    "\0\250\0\250\0\250\0\250\0\250\0\250\0\u0498\0\250"+
    "\0\u04d0\0\u04d0\0\u04d0\0\u0508\0\u0540\0\u04d0\0\u04d0\0\u04d0"+
    "\0\u04d0\0\u04d0\0\u04d0\0\u0578\0\u0118\0\250\0\250\0\u05b0"+
    "\0\u05e8\0\250\0\u0620\0\u0658\0\u0268\0\250\0\250\0\u0690"+
    "\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850"+
    "\0\u0888\0\u08c0\0\u01c0\0\u01c0\0\u08f8\0\u0930\0\u0968\0\u09a0"+
    "\0\u09d8\0\u0a10\0\250\0\u04d0\0\u0a48\0\u0a80\0\u0ab8\0\u0578"+
    "\0\250\0\u0af0\0\u0118\0\u0b28\0\u0b60\0\u0b98\0\u0268\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u01c0\0\u01c0\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20"+
    "\0\u01c0\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8"+
    "\0\u0a48\0\250\0\u0508\0\u0578\0\u0ee0\0\u0f18\0\u0f50\0\u0f88"+
    "\0\u0fc0\0\u01c0\0\u01c0\0\u01c0\0\u01c0\0\u0ff8\0\u1030\0\u01c0"+
    "\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u01c0\0\u01c0\0\u01c0\0\u01c0\0\u01c0"+
    "\0\u01c0\0\u12d0\0\u01c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\4\1\6\1\4\1\10"+
    "\1\4\1\11\1\12\1\13\2\14\1\15\2\4\1\16"+
    "\1\17\1\20\1\14\1\4\1\21\1\22\1\14\1\23"+
    "\1\14\1\24\1\25\1\26\1\14\1\27\1\14\1\30"+
    "\2\14\1\31\2\14\1\32\1\14\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\5\2\6\2\51\1\52"+
    "\1\4\2\51\1\53\2\51\2\54\1\4\2\51\1\16"+
    "\2\51\1\54\2\51\5\54\1\55\14\54\1\56\1\57"+
    "\2\51\1\60\1\61\1\62\6\51\1\63\4\4\1\64"+
    "\63\4\72\0\1\6\65\0\4\65\1\66\1\67\1\65"+
    "\1\70\1\71\7\65\1\0\47\65\10\0\1\72\72\0"+
    "\1\12\67\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\22\14\37\0\1\73\1\74\45\0\1\17\3\0\2\17"+
    "\1\0\5\17\1\0\3\17\1\0\3\17\1\0\2\17"+
    "\1\0\23\17\1\0\14\17\4\75\1\76\1\77\1\75"+
    "\1\100\1\101\7\75\1\0\47\75\13\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\1\14\1\102\20\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\5\14\1\103"+
    "\14\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\5\14\1\104\1\105\13\14\31\0\1\14\1\0\2\14"+
    "\6\0\2\14\1\0\4\14\1\106\7\14\1\107\1\110"+
    "\1\14\1\111\2\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\1\112\12\14\1\113\3\14\1\114\2\14"+
    "\31\0\1\14\1\0\2\14\6\0\2\14\1\0\5\14"+
    "\1\115\14\14\31\0\1\14\1\0\2\14\6\0\2\14"+
    "\1\0\6\14\1\116\2\14\1\117\10\14\31\0\1\14"+
    "\1\0\2\14\6\0\2\14\1\0\1\14\1\120\1\121"+
    "\17\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\6\14\1\122\13\14\104\0\1\123\1\0\1\124\3\0"+
    "\3\124\1\0\7\124\1\125\2\124\1\126\46\124\3\0"+
    "\3\124\1\0\3\124\1\54\1\124\2\54\1\125\2\124"+
    "\1\126\2\124\2\54\1\124\22\54\17\124\3\0\3\124"+
    "\1\0\3\124\1\54\1\124\2\54\1\125\2\124\1\126"+
    "\2\124\2\54\1\124\17\54\1\127\2\54\16\124\1\130"+
    "\1\0\2\130\1\131\1\130\1\0\1\132\10\130\1\0"+
    "\47\130\4\65\1\133\1\67\1\65\1\70\1\71\7\65"+
    "\1\0\60\65\1\134\1\135\1\0\1\65\2\134\6\65"+
    "\1\134\2\65\22\134\15\65\1\134\21\73\1\136\46\73"+
    "\2\74\1\6\65\74\4\75\1\137\1\77\1\75\1\100"+
    "\1\101\7\75\1\0\60\75\1\140\1\141\1\0\1\75"+
    "\2\140\6\75\1\140\2\75\22\140\15\75\1\140\13\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\2\14\1\142"+
    "\17\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\13\14\1\143\6\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\11\14\1\144\10\14\31\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\12\14\1\145\7\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\12\14\1\146"+
    "\7\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\15\14\1\147\4\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\16\14\1\150\3\14\31\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\2\14\1\151\17\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\7\14\1\152"+
    "\12\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\15\14\1\153\4\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\11\14\1\154\10\14\31\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\10\14\1\155\11\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\1\156\21\14"+
    "\31\0\1\14\1\0\2\14\6\0\2\14\1\0\14\14"+
    "\1\157\5\14\31\0\1\14\1\0\2\14\6\0\2\14"+
    "\1\0\5\14\1\160\14\14\31\0\1\161\1\0\2\161"+
    "\6\0\1\161\2\0\22\161\16\0\1\162\3\0\3\162"+
    "\1\0\7\162\1\0\2\162\1\0\45\162\1\124\3\0"+
    "\3\124\1\0\3\124\1\54\1\124\2\54\1\125\2\124"+
    "\1\126\2\124\2\54\1\124\2\54\1\163\17\54\16\124"+
    "\1\130\1\0\2\130\1\164\1\130\1\0\1\132\10\130"+
    "\1\0\47\130\11\0\1\134\1\0\1\134\1\65\3\134"+
    "\5\0\2\134\1\0\22\134\15\0\1\134\13\0\1\165"+
    "\1\0\1\166\52\0\22\73\1\6\45\73\11\0\1\140"+
    "\1\0\1\140\1\75\3\140\5\0\2\140\1\0\22\140"+
    "\15\0\1\140\13\0\1\167\1\0\1\170\65\0\1\14"+
    "\1\0\2\14\6\0\2\14\1\0\3\14\1\171\16\14"+
    "\31\0\1\14\1\0\2\14\6\0\2\14\1\0\11\14"+
    "\1\172\10\14\31\0\1\14\1\0\2\14\6\0\2\14"+
    "\1\0\5\14\1\173\14\14\31\0\1\14\1\0\2\14"+
    "\6\0\2\14\1\0\16\14\1\174\3\14\31\0\1\14"+
    "\1\0\2\14\6\0\2\14\1\0\1\14\1\175\20\14"+
    "\31\0\1\14\1\0\2\14\6\0\2\14\1\0\1\14"+
    "\1\176\20\14\31\0\1\14\1\0\2\14\6\0\2\14"+
    "\1\0\1\14\1\177\20\14\31\0\1\14\1\0\2\14"+
    "\6\0\2\14\1\0\5\14\1\200\14\14\31\0\1\14"+
    "\1\0\2\14\6\0\2\14\1\0\6\14\1\201\13\14"+
    "\31\0\1\14\1\0\2\14\6\0\2\14\1\0\1\202"+
    "\21\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\11\14\1\203\10\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\4\14\1\204\15\14\31\0\1\165\1\65"+
    "\66\0\1\205\2\0\1\205\13\0\1\205\2\0\1\205"+
    "\5\0\3\205\35\0\1\167\1\75\66\0\1\206\2\0"+
    "\1\206\13\0\1\206\2\0\1\206\5\0\3\206\35\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\4\14\1\207"+
    "\15\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\10\14\1\210\11\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\10\14\1\211\11\14\31\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\17\14\1\212\2\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\5\14\1\213"+
    "\14\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\14\14\1\214\5\14\31\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\2\14\1\215\17\14\31\0\1\205\1\65"+
    "\1\0\1\205\13\0\1\205\2\0\1\205\5\0\3\205"+
    "\35\0\1\206\1\75\1\0\1\206\13\0\1\206\2\0"+
    "\1\206\5\0\3\206\35\0\1\14\1\0\2\14\6\0"+
    "\2\14\1\0\5\14\1\216\14\14\31\0\1\14\1\0"+
    "\2\14\6\0\2\14\1\0\11\14\1\217\10\14\31\0"+
    "\1\14\1\0\2\14\6\0\2\14\1\0\2\14\1\220"+
    "\17\14\31\0\1\14\1\0\2\14\6\0\2\14\1\0"+
    "\21\14\1\221\31\0\1\14\1\0\2\14\6\0\2\14"+
    "\1\0\17\14\1\222\2\14\31\0\1\14\1\0\2\14"+
    "\6\0\2\14\1\0\11\14\1\223\10\14\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\2\1\1\11\1\1\1\11"+
    "\1\1\1\11\2\1\1\11\12\1\14\11\1\1\1\11"+
    "\14\1\1\0\2\11\2\0\1\11\3\0\2\11\2\0"+
    "\21\1\1\11\3\0\1\1\1\0\1\11\1\0\1\1"+
    "\3\0\1\1\2\0\20\1\1\11\2\1\4\0\14\1"+
    "\2\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private StringBuffer string = new StringBuffer();
	private int html_count = 0;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;
    
	public Lexer(ComplexSymbolFactory sf) {
		this(new InputStreamReader(System.in));
        symbolFactory = sf;
    }
    
    public Lexer(ComplexSymbolFactory sf, InputStream is) {
		this(is);
		symbolFactory = sf;
	}
            
    public Symbol symbol(String name, int code) {		
    	//System.out.println("state: " + yystate() + " name: " + name + " code: " + code + " line: " + (yyline+1));
		return symbolFactory.newSymbol(name, code,new Location(yyline+1,yycolumn+1-yylength()),new Location(yyline+1,yycolumn+1));
    }
    
    public Symbol symbol(String name, int code, Object lexem){
    	//System.out.println("state: " + yystate() + " name: " + name + " code: " + code + " lexem: " + lexem.toString() + " line: " + (yyline+1));		
		return symbolFactory.newSymbol(name, code, new Location(yyline+1, yycolumn +1), new Location(yyline+1,yycolumn+yylength()), lexem);
    }    
    
    private void error(String message) {
    	System.err.println("Error at line "+(yyline+1)+", column "+(yycolumn+1)+" : "+message);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 32: 
          { yybegin(YYINITIAL); return symbol("StrCon", sym.STRCON, yytext());
          }
        case 50: break;
        case 46: 
          { return symbol("Import", sym.IMPORT);
          }
        case 51: break;
        case 11: 
          { return symbol("Left Parenthesis", sym.LPAREN);
          }
        case 52: break;
        case 43: 
          { return symbol("CDATA", sym.CDATA);
          }
        case 53: break;
        case 9: 
          { return symbol("SymbolCon", sym.SYMBOLCON, yytext());
          }
        case 54: break;
        case 7: 
          { return symbol("Dot", sym.DOT);
          }
        case 55: break;
        case 35: 
          { yybegin(YYINITIAL); return symbol("End", sym.END);
          }
        case 56: break;
        case 19: 
          { return symbol("Left brackets", sym.LBRACKET);
          }
        case 57: break;
        case 41: 
          { return symbol("Echo", sym.ECHO);
          }
        case 58: break;
        case 30: 
          { return symbol("In", sym.IN);
          }
        case 59: break;
        case 27: 
          { return symbol("PostText", sym.POSTTEXT, yytext());
          }
        case 60: break;
        case 18: 
          { return symbol("Assign", sym.ASSIGN);
          }
        case 61: break;
        case 23: 
          { return symbol("Colon", sym.COLON);
          }
        case 62: break;
        case 49: 
          { yybegin(COMMENT); return symbol("Comment", sym.COMMENT);
          }
        case 63: break;
        case 16: 
          { return symbol("At sign", sym.AT_SIGN);
          }
        case 64: break;
        case 37: 
          // lookahead expression with fixed lookahead length
          yypushback(2);
          { return symbol("Directory", sym.DIRECTORY, yytext());
          }
        case 65: break;
        case 4: 
          { return symbol("NatCon", sym.NATCON, new Integer(Integer.parseInt(yytext())));
          }
        case 66: break;
        case 14: 
          { return symbol("Right braces", sym.RBRACE);
          }
        case 67: break;
        case 40: 
          { return symbol("Each", sym.EACH);
          }
        case 68: break;
        case 34: 
          { return symbol("Let", sym.LET);
          }
        case 69: break;
        case 2: 
          { /* Negeren */
          }
        case 70: break;
        case 39: 
          { return symbol("Else", sym.ELSE);
          }
        case 71: break;
        case 1: 
          { error("Illegal character <"+ yytext()+">");
          }
        case 72: break;
        case 45: 
          { return symbol("Module constant", MODULE);
          }
        case 73: break;
        case 24: 
          { return symbol("Text", sym.TEXT, yytext());
          }
        case 74: break;
        case 33: 
          { return symbol("Def", sym.DEF);
          }
        case 75: break;
        case 8: 
          { return symbol("Slash", sym.SLASH);
          }
        case 76: break;
        case 21: 
          { return symbol("Questionmark", sym.QUESTIONMARK);
          }
        case 77: break;
        case 17: 
          { return symbol("Percent sign", sym.PERCENT_SIGN);
          }
        case 78: break;
        case 31: 
          { return symbol("Or", sym.OR);
          }
        case 79: break;
        case 26: 
          { return symbol("And", sym.AND);
          }
        case 80: break;
        case 10: 
          { return symbol("Comma", sym.COMMA);
          }
        case 81: break;
        case 3: 
          { return symbol("Number sign", sym.NUMBER_SIGN);
          }
        case 82: break;
        case 44: 
          { return symbol("Yield", sym.YIELD);
          }
        case 83: break;
        case 13: 
          { return symbol("Left braces", sym.LBRACE);
          }
        case 84: break;
        case 22: 
          { return symbol("Exclamation", sym.EXCLAMATION);
          }
        case 85: break;
        case 47: 
          { return symbol("Record", sym.RECORD);
          }
        case 86: break;
        case 28: 
          { return symbol("MidText", sym.MIDTEXT, yytext());
          }
        case 87: break;
        case 20: 
          { return symbol("Right brackets", sym.RBRACKET);
          }
        case 88: break;
        case 38: 
          { return symbol("List", sym.LIST);
          }
        case 89: break;
        case 36: 
          { return symbol("Filename", sym.FILENAME, yytext());
          }
        case 90: break;
        case 12: 
          { return symbol("Right parenthesis", sym.RPAREN);
          }
        case 91: break;
        case 15: 
          { return symbol("Dollar sign", sym.DOLLAR_SIGN);
          }
        case 92: break;
        case 42: 
          { yybegin(SITE); return symbol("Site", sym.SITE);
          }
        case 93: break;
        case 5: 
          { return symbol("Semicolon", sym.SEMI);
          }
        case 94: break;
        case 29: 
          { return symbol("If", sym.IF);
          }
        case 95: break;
        case 48: 
          { return symbol("String", sym.STRING);
          }
        case 96: break;
        case 6: 
          { return symbol("IdCon", sym.IDCON, yytext());
          }
        case 97: break;
        case 25: 
          { return symbol("PreText", sym.PRETEXT, yytext());
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
