//
// Generated by JTB 1.3.2
//

package WaeberLexer.visitor;
import WaeberLexer.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

@SuppressWarnings("all")
public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expression()
    * f1 -> <ENDOFFILE>
    */
   public R visit(Start n);

   /**
    * f0 -> ( <MODULE> | <SITE> | <END> | <DEF> | <ECHO> | <YIELD> | <EACH> | <IF> | <LET> | <COMMENT> | <CDATA> | <IMPORT> | <IDENTIFIER> | <INTEGER_LITERAL> | <PLUS> | <MINUS> | <IS> | <OPAR> | <CPAR> | <OBRACE> | <CBRACE> | <SLASH> | <DOT> | <COLON> | <QUOTATION> | <SEMICOLON> | <COMMA> | <AMPERSAND> | <FLOATINGPOINT> | <AT> )*
    */
   public R visit(Expression n);

   /**

    */
   public R visit(AdditiveExpression n);

   /**

    */
   public R visit(MultiplicativeExpression n);

   /**

    */
   public R visit(UnaryExpression n);

   /**

    */
   public R visit(Identifier n);

   /**

    */
   public R visit(MyInteger n);

}

