//
// Generated by JTB 1.3.2
//

package WaeberLexer.visitor;
import WaeberLexer.syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

@SuppressWarnings("all")
public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expression()
    * f1 -> <ENDOFFILE>
    */
   public void visit(Start n, A argu);

   /**
    * f0 -> ( <MODULE> | <SITE> | <END> | <DEF> | <ECHO> | <YIELD> | <EACH> | <IF> | <LET> | <COMMENT> | <CDATA> | <IMPORT> | <IDENTIFIER> | <INTEGER_LITERAL> | <PLUS> | <MINUS> | <IS> | <OPAR> | <CPAR> | <OBRACE> | <CBRACE> | <SLASH> | <DOT> | <COLON> | <QUOTATION> | <SEMICOLON> | <COMMA> | <AMPERSAND> | <FLOATINGPOINT> | <AT> )*
    */
   public void visit(Expression n, A argu);

   /**

    */
   public void visit(AdditiveExpression n, A argu);

   /**

    */
   public void visit(MultiplicativeExpression n, A argu);

   /**

    */
   public void visit(UnaryExpression n, A argu);

   /**

    */
   public void visit(Identifier n, A argu);

   /**

    */
   public void visit(MyInteger n, A argu);

}

