/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionTypePredicateNoAndOr extends PPredicateNoAndOr
{
    private PExpression _expression_;
    private TColon _colon_;
    private PType _type_;
    private TQuestionMark _questionMark_;

    public AExpressionTypePredicateNoAndOr()
    {
        // Constructor
    }

    public AExpressionTypePredicateNoAndOr(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TQuestionMark _questionMark_)
    {
        // Constructor
        setExpression(_expression_);

        setColon(_colon_);

        setType(_type_);

        setQuestionMark(_questionMark_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionTypePredicateNoAndOr(
            cloneNode(this._expression_),
            cloneNode(this._colon_),
            cloneNode(this._type_),
            cloneNode(this._questionMark_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionTypePredicateNoAndOr(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TQuestionMark getQuestionMark()
    {
        return this._questionMark_;
    }

    public void setQuestionMark(TQuestionMark node)
    {
        if(this._questionMark_ != null)
        {
            this._questionMark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._questionMark_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._colon_)
            + toString(this._type_)
            + toString(this._questionMark_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._questionMark_ == child)
        {
            this._questionMark_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._questionMark_ == oldChild)
        {
            setQuestionMark((TQuestionMark) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
