/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AImport extends PImport
{
    private TImport _import_;
    private PModuleId _moduleId_;

    public AImport()
    {
        // Constructor
    }

    public AImport(
        @SuppressWarnings("hiding") TImport _import_,
        @SuppressWarnings("hiding") PModuleId _moduleId_)
    {
        // Constructor
        setImport(_import_);

        setModuleId(_moduleId_);

    }

    @Override
    public Object clone()
    {
        return new AImport(
            cloneNode(this._import_),
            cloneNode(this._moduleId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImport(this);
    }

    public TImport getImport()
    {
        return this._import_;
    }

    public void setImport(TImport node)
    {
        if(this._import_ != null)
        {
            this._import_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._import_ = node;
    }

    public PModuleId getModuleId()
    {
        return this._moduleId_;
    }

    public void setModuleId(PModuleId node)
    {
        if(this._moduleId_ != null)
        {
            this._moduleId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moduleId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._import_)
            + toString(this._moduleId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._import_ == child)
        {
            this._import_ = null;
            return;
        }

        if(this._moduleId_ == child)
        {
            this._moduleId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._import_ == oldChild)
        {
            setImport((TImport) newChild);
            return;
        }

        if(this._moduleId_ == oldChild)
        {
            setModuleId((PModuleId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
