/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleFormal extends PFormal
{
    private PFormal _formal_;
    private TComma _comma_;
    private TIdCon _idCon_;

    public AMultipleFormal()
    {
        // Constructor
    }

    public AMultipleFormal(
        @SuppressWarnings("hiding") PFormal _formal_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") TIdCon _idCon_)
    {
        // Constructor
        setFormal(_formal_);

        setComma(_comma_);

        setIdCon(_idCon_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleFormal(
            cloneNode(this._formal_),
            cloneNode(this._comma_),
            cloneNode(this._idCon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleFormal(this);
    }

    public PFormal getFormal()
    {
        return this._formal_;
    }

    public void setFormal(PFormal node)
    {
        if(this._formal_ != null)
        {
            this._formal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formal_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public TIdCon getIdCon()
    {
        return this._idCon_;
    }

    public void setIdCon(TIdCon node)
    {
        if(this._idCon_ != null)
        {
            this._idCon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idCon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formal_)
            + toString(this._comma_)
            + toString(this._idCon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formal_ == child)
        {
            this._formal_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._idCon_ == child)
        {
            this._idCon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formal_ == oldChild)
        {
            setFormal((PFormal) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._idCon_ == oldChild)
        {
            setIdCon((TIdCon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
