/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class ANoPlusExpression extends PExpression
{
    private PExpressionNoPlus _expressionNoPlus_;

    public ANoPlusExpression()
    {
        // Constructor
    }

    public ANoPlusExpression(
        @SuppressWarnings("hiding") PExpressionNoPlus _expressionNoPlus_)
    {
        // Constructor
        setExpressionNoPlus(_expressionNoPlus_);

    }

    @Override
    public Object clone()
    {
        return new ANoPlusExpression(
            cloneNode(this._expressionNoPlus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoPlusExpression(this);
    }

    public PExpressionNoPlus getExpressionNoPlus()
    {
        return this._expressionNoPlus_;
    }

    public void setExpressionNoPlus(PExpressionNoPlus node)
    {
        if(this._expressionNoPlus_ != null)
        {
            this._expressionNoPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionNoPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionNoPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionNoPlus_ == child)
        {
            this._expressionNoPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionNoPlus_ == oldChild)
        {
            setExpressionNoPlus((PExpressionNoPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
