/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class ARecordType extends PType
{
    private TRecord _record_;

    public ARecordType()
    {
        // Constructor
    }

    public ARecordType(
        @SuppressWarnings("hiding") TRecord _record_)
    {
        // Constructor
        setRecord(_record_);

    }

    @Override
    public Object clone()
    {
        return new ARecordType(
            cloneNode(this._record_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecordType(this);
    }

    public TRecord getRecord()
    {
        return this._record_;
    }

    public void setRecord(TRecord node)
    {
        if(this._record_ != null)
        {
            this._record_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._record_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._record_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._record_ == child)
        {
            this._record_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._record_ == oldChild)
        {
            setRecord((TRecord) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
