/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class ASingleKeyValuePairs extends PKeyValuePairs
{
    private PKeyValuePair _keyValuePair_;

    public ASingleKeyValuePairs()
    {
        // Constructor
    }

    public ASingleKeyValuePairs(
        @SuppressWarnings("hiding") PKeyValuePair _keyValuePair_)
    {
        // Constructor
        setKeyValuePair(_keyValuePair_);

    }

    @Override
    public Object clone()
    {
        return new ASingleKeyValuePairs(
            cloneNode(this._keyValuePair_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleKeyValuePairs(this);
    }

    public PKeyValuePair getKeyValuePair()
    {
        return this._keyValuePair_;
    }

    public void setKeyValuePair(PKeyValuePair node)
    {
        if(this._keyValuePair_ != null)
        {
            this._keyValuePair_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyValuePair_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyValuePair_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyValuePair_ == child)
        {
            this._keyValuePair_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyValuePair_ == oldChild)
        {
            setKeyValuePair((PKeyValuePair) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
