/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AStatementAssignment extends PAssignment
{
    private TIdCon _idCon_;
    private PFormals _formals_;
    private TAssign _assign_;
    private PStatement _statement_;

    public AStatementAssignment()
    {
        // Constructor
    }

    public AStatementAssignment(
        @SuppressWarnings("hiding") TIdCon _idCon_,
        @SuppressWarnings("hiding") PFormals _formals_,
        @SuppressWarnings("hiding") TAssign _assign_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setIdCon(_idCon_);

        setFormals(_formals_);

        setAssign(_assign_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AStatementAssignment(
            cloneNode(this._idCon_),
            cloneNode(this._formals_),
            cloneNode(this._assign_),
            cloneNode(this._statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementAssignment(this);
    }

    public TIdCon getIdCon()
    {
        return this._idCon_;
    }

    public void setIdCon(TIdCon node)
    {
        if(this._idCon_ != null)
        {
            this._idCon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idCon_ = node;
    }

    public PFormals getFormals()
    {
        return this._formals_;
    }

    public void setFormals(PFormals node)
    {
        if(this._formals_ != null)
        {
            this._formals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formals_ = node;
    }

    public TAssign getAssign()
    {
        return this._assign_;
    }

    public void setAssign(TAssign node)
    {
        if(this._assign_ != null)
        {
            this._assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assign_ = node;
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idCon_)
            + toString(this._formals_)
            + toString(this._assign_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idCon_ == child)
        {
            this._idCon_ = null;
            return;
        }

        if(this._formals_ == child)
        {
            this._formals_ = null;
            return;
        }

        if(this._assign_ == child)
        {
            this._assign_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idCon_ == oldChild)
        {
            setIdCon((TIdCon) newChild);
            return;
        }

        if(this._formals_ == oldChild)
        {
            setFormals((PFormals) newChild);
            return;
        }

        if(this._assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
