/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class TModuleKeyword extends Token
{
    public TModuleKeyword()
    {
        super.setText("module");
    }

    public TModuleKeyword(int line, int pos)
    {
        super.setText("module");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TModuleKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTModuleKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TModuleKeyword text.");
    }
}
