/* Generated By:JJTree: Do not edit this line. ASTLeftFactoring.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTLeftFactoring extends SimpleNode {
  public ASTLeftFactoring(int id) {
    super(id);
  }

  public ASTLeftFactoring(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bee1cd79c3d073cee24926048126db03 (do not edit this line) */
