/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTModule extends SimpleNode {
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1dd392efd5039d2dbbae81ef5c0935c (do not edit this line) */
