/* Generated By:JJTree: Do not edit this line. ASTDesignator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTDesignator extends SimpleNode {
  public ASTDesignator(int id) {
    super(id);
  }

  public ASTDesignator(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=99c71db0352eebd5d5ce85d6f64fbc9f (do not edit this line) */
