/* Generated By:JJTree: Do not edit this line. ASTmarkupmarkup.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTmarkupmarkup extends SimpleNode {
  public ASTmarkupmarkup(int id) {
    super(id);
  }

  public ASTmarkupmarkup(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c210d80bf0a4c9c1512a6116ba6cfe7a (do not edit this line) */
