/* Generated By:JJTree: Do not edit this line. ASTMoreMarkup.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTMoreMarkup extends SimpleNode {
  public ASTMoreMarkup(int id) {
    super(id);
  }

  public ASTMoreMarkup(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11d24b962222f00c23aab29262ea9295 (do not edit this line) */
