/* Generated By:JJTree: Do not edit this line. ASTModuleElement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTModuleElement extends SimpleNode {
  public ASTModuleElement(int id) {
    super(id);
  }

  public ASTModuleElement(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aacfd187026a7ec34b46e98dc770d444 (do not edit this line) */
