/* Generated By:JJTree: Do not edit this line. ASTmarkupembedding.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTmarkupembedding extends SimpleNode {
  public ASTmarkupembedding(int id) {
    super(id);
  }

  public ASTmarkupembedding(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c41ab1316caead7ce8ac0e7cb6a950ab (do not edit this line) */
