package waebric.javacc;
/* Generated By:JJTree: Do not edit this line. ASTTextTail.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTTextTail extends SimpleNode {
  public ASTTextTail(int id) {
    super(id);
  }

  public ASTTextTail(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=619e5853538515c4901507d9ed04a623 (do not edit this line) */
