package waebric.javacc;
/* Generated By:JJTree: Do not edit this line. ASTImport.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTImport extends SimpleNode {
  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc2677c2a9603c827d157a17118ad3d2 (do not edit this line) */
