package waebric.javacc;
/* Generated By:JJTree: Do not edit this line. ASTPredicate.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTPredicate extends SimpleNode {
  public ASTPredicate(int id) {
    super(id);
  }

  public ASTPredicate(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9fa50cb95da17f2327466ac72c522a43 (do not edit this line) */
