package waebric.javacc;
/* Generated By:JJTree: Do not edit this line. ASTSite.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class ASTSite extends SimpleNode {
  public ASTSite(int id) {
    super(id);
  }

  public ASTSite(WaebricParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WaebricParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed21a048fbd0bc7e4282ccc4f17c4e06 (do not edit this line) */
