importPackage(java.io)

load("lib.js")
load("ometa-base.js")
load("parser.js")
load("bs-js-compiler.js")
load("bs-ometa-compiler.js")
load("bs-ometa-optimizer.js")
load("bs-ometa-js-compiler.js")

load("../classes/Module.js")
load("../classes/ModuleElement.js")
load("../classes/Import.js")
load("../classes/ModuleId.js")

/**
 * Returns the Waebric grammar written in OMeta for parsing
 * 
 * @return Waebric parser (String)
 */
getParser = function() {
	fis = new FileInputStream('../parser.ometa');
	bis = new BufferedInputStream(fis);
	dis = new DataInputStream(bis);

	parser = '';
	while(dis.available() != 0){
		parser += dis.readLine() + '\n';
	}
	fis.close();
	bis.close();
	dis.close();
	return parser;
}

/**
 * Returns the Waebric grammar written in OMeta for interpreting
 * 
 * @return Waebric interpreter (String)
 */
getInterpreter = function() {
	fis = new FileInputStream('../interpreter.ometa');
    bis = new BufferedInputStream(fis);
    dis = new DataInputStream(bis);

    interpreter = '';
    while(dis.available() != 0){
    	interpreter += dis.readLine() + '\n';
    }
    fis.close();
    bis.close();
    dis.close();
    return interpreter;
}

/**
 * Returns a waebric program
 * 
 * @return Waebric program (String)
 */
getProgram = function() {
    fis = new FileInputStream('../program.wae');
    bis = new BufferedInputStream(fis);
    dis = new DataInputStream(bis);

    program = '';
    while(dis.available() != 0){
    	program += dis.readLine() + '\n';
	}
	fis.close();
	bis.close();
	dis.close();
	return program;
}

/**
 * Returns the input for Rhino commandline
 * 
 * @return Input rhino (String)
 */
getSource = function(){
	program = getProgram();

	source 	= getParser() + ';'
	        + 'tree = WaebricParser.matchAll(program, "Module");'
	        + 'alert("\n");'
	        + 'alert("\n");'
	        + 'alert("\n");'
	        + 'alert("--------------------------------------------------------------------------------------------------------");'
	        + 'alert(tree);'
	        + 'alert("--------------------------------------------------------------------------------------------------------");'
	        + 'alert("\n");'
	        + 'alert("\n");'
	        + 'alert("\n");'
			+ getInterpreter() + ';'
			+ 'html_output = WaebricInterpreter.match(tree, "interp");'
			+ 'alert(module.moduleElements);' 

	return source;
}

/**
 * Parse and interprete the waebric program
 * First, the Abstract Syntax Tree is generated by the Waebric parser as a String.
 * Then, the Abstract Syntax Tree is converted to a data object by the interpreter
 * 
 * @return Output of the Waebric parser (AST)
 * @return Output of the Waebric interpreter (DATA OBJECT)
 */
translateCode = function(source) {
	var translationError = function(m, i) { alert("Translation error - please tell Alex about this!"); throw fail },
    tree = BSOMetaJSParser.matchAll(source, "topLevel", undefined, function(m, i) { throw fail.delegated({errorPos: i}) })
  	return BSOMetaJSTranslator.match(tree, "trans", undefined, translationError)
}

/**
 * Replace alert method with print method to enable output in Rhino
 */
alert = print

/**
 * Evaluate the waebric parser and interpreter and display the output
 */
eval(translateCode(getSource()));