/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class ACdataStatementNoMarkupNoShortIf extends PStatementNoMarkupNoShortIf
{
    private TCdata _cdata_;
    private PExpression _expression_;
    private TSemiColon _semiColon_;

    public ACdataStatementNoMarkupNoShortIf()
    {
        // Constructor
    }

    public ACdataStatementNoMarkupNoShortIf(
        @SuppressWarnings("hiding") TCdata _cdata_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TSemiColon _semiColon_)
    {
        // Constructor
        setCdata(_cdata_);

        setExpression(_expression_);

        setSemiColon(_semiColon_);

    }

    @Override
    public Object clone()
    {
        return new ACdataStatementNoMarkupNoShortIf(
            cloneNode(this._cdata_),
            cloneNode(this._expression_),
            cloneNode(this._semiColon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACdataStatementNoMarkupNoShortIf(this);
    }

    public TCdata getCdata()
    {
        return this._cdata_;
    }

    public void setCdata(TCdata node)
    {
        if(this._cdata_ != null)
        {
            this._cdata_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cdata_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TSemiColon getSemiColon()
    {
        return this._semiColon_;
    }

    public void setSemiColon(TSemiColon node)
    {
        if(this._semiColon_ != null)
        {
            this._semiColon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semiColon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cdata_)
            + toString(this._expression_)
            + toString(this._semiColon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cdata_ == child)
        {
            this._cdata_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._semiColon_ == child)
        {
            this._semiColon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cdata_ == oldChild)
        {
            setCdata((TCdata) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._semiColon_ == oldChild)
        {
            setSemiColon((TSemiColon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
