/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class ADesignatorMarkup extends PMarkup
{
    private PDesignator _designator_;

    public ADesignatorMarkup()
    {
        // Constructor
    }

    public ADesignatorMarkup(
        @SuppressWarnings("hiding") PDesignator _designator_)
    {
        // Constructor
        setDesignator(_designator_);

    }

    @Override
    public Object clone()
    {
        return new ADesignatorMarkup(
            cloneNode(this._designator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADesignatorMarkup(this);
    }

    public PDesignator getDesignator()
    {
        return this._designator_;
    }

    public void setDesignator(PDesignator node)
    {
        if(this._designator_ != null)
        {
            this._designator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._designator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._designator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._designator_ == child)
        {
            this._designator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._designator_ == oldChild)
        {
            setDesignator((PDesignator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
