/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AEchoEmbeddingStatement extends PStatement
{
    private PEmbedding _embedding_;

    public AEchoEmbeddingStatement()
    {
        // Constructor
    }

    public AEchoEmbeddingStatement(
        @SuppressWarnings("hiding") PEmbedding _embedding_)
    {
        // Constructor
        setEmbedding(_embedding_);

    }

    @Override
    public Object clone()
    {
        return new AEchoEmbeddingStatement(
            cloneNode(this._embedding_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEchoEmbeddingStatement(this);
    }

    public PEmbedding getEmbedding()
    {
        return this._embedding_;
    }

    public void setEmbedding(PEmbedding node)
    {
        if(this._embedding_ != null)
        {
            this._embedding_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._embedding_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._embedding_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._embedding_ == child)
        {
            this._embedding_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._embedding_ == oldChild)
        {
            setEmbedding((PEmbedding) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
