/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AMapping extends PMapping
{
    private PPath _path_;
    private PMarkup _markup_;

    public AMapping()
    {
        // Constructor
    }

    public AMapping(
        @SuppressWarnings("hiding") PPath _path_,
        @SuppressWarnings("hiding") PMarkup _markup_)
    {
        // Constructor
        setPath(_path_);

        setMarkup(_markup_);

    }

    @Override
    public Object clone()
    {
        return new AMapping(
            cloneNode(this._path_),
            cloneNode(this._markup_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMapping(this);
    }

    public PPath getPath()
    {
        return this._path_;
    }

    public void setPath(PPath node)
    {
        if(this._path_ != null)
        {
            this._path_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    public PMarkup getMarkup()
    {
        return this._markup_;
    }

    public void setMarkup(PMarkup node)
    {
        if(this._markup_ != null)
        {
            this._markup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._markup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._path_)
            + toString(this._markup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._path_ == child)
        {
            this._path_ = null;
            return;
        }

        if(this._markup_ == child)
        {
            this._markup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._path_ == oldChild)
        {
            setPath((PPath) newChild);
            return;
        }

        if(this._markup_ == oldChild)
        {
            setMarkup((PMarkup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
