/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import java.util.*;
import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AMarkupMarkupEmbed extends PEmbed
{
    private final LinkedList<PMarkup> _multiple_ = new LinkedList<PMarkup>();
    private PMarkupNoShortMarkup _single_;

    public AMarkupMarkupEmbed()
    {
        // Constructor
    }

    public AMarkupMarkupEmbed(
        @SuppressWarnings("hiding") List<PMarkup> _multiple_,
        @SuppressWarnings("hiding") PMarkupNoShortMarkup _single_)
    {
        // Constructor
        setMultiple(_multiple_);

        setSingle(_single_);

    }

    @Override
    public Object clone()
    {
        return new AMarkupMarkupEmbed(
            cloneList(this._multiple_),
            cloneNode(this._single_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMarkupMarkupEmbed(this);
    }

    public LinkedList<PMarkup> getMultiple()
    {
        return this._multiple_;
    }

    public void setMultiple(List<PMarkup> list)
    {
        this._multiple_.clear();
        this._multiple_.addAll(list);
        for(PMarkup e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PMarkupNoShortMarkup getSingle()
    {
        return this._single_;
    }

    public void setSingle(PMarkupNoShortMarkup node)
    {
        if(this._single_ != null)
        {
            this._single_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._single_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiple_)
            + toString(this._single_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiple_.remove(child))
        {
            return;
        }

        if(this._single_ == child)
        {
            this._single_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PMarkup> i = this._multiple_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMarkup) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._single_ == oldChild)
        {
            setSingle((PMarkupNoShortMarkup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
