/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.grammar.waebric.node;

import org.sablecc.grammar.waebric.analysis.*;

@SuppressWarnings("nls")
public final class AOrPredicate extends PPredicate
{
    private PPredicate _left_;
    private PPredicate _right_;

    public AOrPredicate()
    {
        // Constructor
    }

    public AOrPredicate(
        @SuppressWarnings("hiding") PPredicate _left_,
        @SuppressWarnings("hiding") PPredicate _right_)
    {
        // Constructor
        setLeft(_left_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AOrPredicate(
            cloneNode(this._left_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrPredicate(this);
    }

    public PPredicate getLeft()
    {
        return this._left_;
    }

    public void setLeft(PPredicate node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public PPredicate getRight()
    {
        return this._right_;
    }

    public void setRight(PPredicate node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PPredicate) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PPredicate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
