/*
 * Generated by classgen, version 1.5
 * 6/16/09 8:42 PM
 */
package waebric.node;

public class IfElse extends Statement {

  public Predicate p;
  public Statement s1;
  public Statement s2;

  public IfElse (Predicate p, Statement s1, Statement s2) {
    this.p = p;
    if (p != null) p.setParent(this);
    this.s1 = s1;
    if (s1 != null) s1.setParent(this);
    this.s2 = s2;
    if (s2 != null) s2.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (p != null) p.accept(visitor);
    if (s1 != null) s1.accept(visitor);
    if (s2 != null) s2.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (p != null) p.traverseTopDown(visitor);
    if (s1 != null) s1.traverseTopDown(visitor);
    if (s2 != null) s2.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (p != null) p.traverseBottomUp(visitor);
    if (s1 != null) s1.traverseBottomUp(visitor);
    if (s2 != null) s2.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("IfElse(\n");
      if (p != null)
        buffer.append(p.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (s1 != null)
        buffer.append(s1.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (s2 != null)
        buffer.append(s2.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [IfElse]");
    return buffer.toString();
  }
}
