/*
 * Generated by classgen, version 1.5
 * 6/16/09 7:49 PM
 */
package waebric.node;

public class Record extends Expression {

  public KeyvaluepairList keyvaluepairList;

  public Record (KeyvaluepairList keyvaluepairList) {
    this.keyvaluepairList = keyvaluepairList;
    if (keyvaluepairList != null) keyvaluepairList.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (keyvaluepairList != null) keyvaluepairList.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (keyvaluepairList != null) keyvaluepairList.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (keyvaluepairList != null) keyvaluepairList.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Record(\n");
      if (keyvaluepairList != null)
        buffer.append(keyvaluepairList.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Record]");
    return buffer.toString();
  }
}
