/*
 * Generated by classgen, version 1.5
 * 7/30/09 10:24 AM
 */

package waebric.node;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
