/*
 * Generated by classgen, version 1.5
 * 6/16/09 7:49 PM
 */
package waebric.node;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(ModuleElementList moduleElementList) { visit(); }
  public void visit(ModuleId moduleId) { visit(); }
  public void visit(MappingList mappingList) { visit(); }
  public void visit(FormalList formalList) { visit(); }
  public void visit(StatementList statementList) { visit(); }
  public void visit(AssignmentList assignmentList) { visit(); }
  public void visit(ExpressionList expressionList) { visit(); }
  public void visit(KeyvaluepairList keyvaluepairList) { visit(); }
  public void visit(MarkupList markupList) { visit(); }
  public void visit(AttribuutList attribuutList) { visit(); }
  public void visit(Args args) { visit(); }
  public void visit(Module module) { visit(); }
  public void visit(Mapping mapping) { visit(); }
  public void visit(Path path) { visit(); }
  public void visit(Keyvaluepair keyvaluepair) { visit(); }
  public void visit(Dummy dummy) { visit(); }
  public void visit(ModuleElement moduleElement) { visit(); }
  public void visit(Site site) { visit(); }
  public void visit(ImportDeclaration importDeclaration) { visit(); }
  public void visit(Def def) { visit(); }
  public void visit(Embed embed) { visit(); }
  public void visit(ExpEmbedding expEmbedding) { visit(); }
  public void visit(MarkupEmbedding markupEmbedding) { visit(); }
  public void visit(Texttail texttail) { visit(); }
  public void visit(Post post) { visit(); }
  public void visit(Mid mid) { visit(); }
  public void visit(Embedding embedding) { visit(); }
  public void visit(Embedding0 embedding0) { visit(); }
  public void visit(Pre pre) { visit(); }
  public void visit(Statement statement) { visit(); }
  public void visit(Opmaak opmaak) { visit(); }
  public void visit(MarkupMarkup markupMarkup) { visit(); }
  public void visit(MarkupStat markupStat) { visit(); }
  public void visit(MarkupExp markupExp) { visit(); }
  public void visit(CData cData) { visit(); }
  public void visit(Echo echo) { visit(); }
  public void visit(EchoEmbedding echoEmbedding) { visit(); }
  public void visit(Yield yield) { visit(); }
  public void visit(Comment comment) { visit(); }
  public void visit(Let let) { visit(); }
  public void visit(Each each) { visit(); }
  public void visit(Iff iff) { visit(); }
  public void visit(IfElse ifElse) { visit(); }
  public void visit(MarkupEmbeddingg markupEmbeddingg) { visit(); }
  public void visit(Statement15 statement15) { visit(); }
  public void visit(Block block) { visit(); }
  public void visit(Tiepe tiepe) { visit(); }
  public void visit(ListType listType) { visit(); }
  public void visit(RecordType recordType) { visit(); }
  public void visit(StringType stringType) { visit(); }
  public void visit(Predicate predicate) { visit(); }
  public void visit(Predicate0 predicate0) { visit(); }
  public void visit(IsA isA) { visit(); }
  public void visit(Not not) { visit(); }
  public void visit(And and) { visit(); }
  public void visit(Or or) { visit(); }
  public void visit(Assignment assignment) { visit(); }
  public void visit(VarBind varBind) { visit(); }
  public void visit(FuncBind funcBind) { visit(); }
  public void visit(Expression expression) { visit(); }
  public void visit(List list) { visit(); }
  public void visit(Var var) { visit(); }
  public void visit(Symb symb) { visit(); }
  public void visit(Num num) { visit(); }
  public void visit(Text text) { visit(); }
  public void visit(Record record) { visit(); }
  public void visit(Markup markup) { visit(); }
  public void visit(Markup0 markup0) { visit(); }
  public void visit(Call call) { visit(); }
  public void visit(Formal formal) { visit(); }
  public void visit(Formal0 formal0) { visit(); }
  public void visit(Empty empty) { visit(); }
  public void visit(Designator designator) { visit(); }
  public void visit(Designator0 designator0) { visit(); }
  public void visit(Tag tag) { visit(); }
  public void visit(Attribuut attribuut) { visit(); }
  public void visit(Id id) { visit(); }
  public void visit(Classs classs) { visit(); }
  public void visit(Name name) { visit(); }
  public void visit(Type type) { visit(); }
  public void visit(WidthHeight widthHeight) { visit(); }
  public void visit(Height height) { visit(); }
  public void visit(Argument argument) { visit(); }
  public void visit(Argument0 argument0) { visit(); }
  public void visit(Attri attri) { visit(); }

  public void visit() { }

}
