/*
 * Generated by classgen, version 1.5
 * 6/16/09 7:49 PM
 */
package waebric.node;

public class MarkupEmbeddingg extends Statement {

  public MarkupList ml;
  public Embedding e;

  public MarkupEmbeddingg (MarkupList ml, Embedding e) {
    this.ml = ml;
    if (ml != null) ml.setParent(this);
    this.e = e;
    if (e != null) e.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (ml != null) ml.accept(visitor);
    if (e != null) e.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (ml != null) ml.traverseTopDown(visitor);
    if (e != null) e.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (ml != null) ml.traverseBottomUp(visitor);
    if (e != null) e.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("MarkupEmbeddingg(\n");
      if (ml != null)
        buffer.append(ml.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (e != null)
        buffer.append(e.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [MarkupEmbeddingg]");
    return buffer.toString();
  }
}
