/*
 * Generated by classgen, version 1.5
 * 6/16/09 7:49 PM
 */

package waebric.node;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
