/*
 * Generated by classgen, version 1.5
 * 7/30/09 10:24 AM
 */

package waebric.node;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
